In [11]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

In [216]:
def init(d, N):
#     np.random.seed(2)
    line_points = np.random.uniform(-1, 1, size=[2, 2])
    lr = LinearRegression(fit_intercept=True)
    lr.fit(line_points[:,0].reshape(-1, 1), line_points[:,1])
    line_coef = [lr.intercept_, lr.coef_]
    X = np.random.uniform(-1, 1, size=[N, d])
    
#     line_coef = list()
#     line_coef.append((line_points[1,0]-line_points[1,1])/(line_points[0,0]-line_points[0,1]))
#     line_coef.append(line_points[1,0]-line_coef[-1]*line_points[0,0])
#     line_coef = np.array(line_coef)

    
    y = X[:, 1] - X[:, 0] * line_coef[1] - line_coef[0] >= 0
    y = np.where(y, 1, -1)
    
    return X, y, line_coef

In [217]:
def plot(X, y, w):
    plt.figure(figsize=(10, 7))
    plt.scatter(X[y==-1,0], X[y==-1,1], c='r', s=100)
    plt.scatter(X[y==1,0], X[y==1,1], c='g', s=100)
    x_plot = np.linspace(min(X[:,0])-.5, max(X[:,1])+.5)
    y_plot = -w[1]/w[2]*x_plot - w[0]/w[2]
    plt.plot(x_plot, y_plot)

In [256]:
def make_grid(n_points=1000):
    x = np.linspace(-1, 1, n_points)
    grid = []
    for i in range(n_points):
        for j in range(n_points):
            grid.append([x[i], x[j]])
    return np.array(grid)

In [264]:
def pla(X, y):
    w = np.zeros(X.shape[1])
    loop = 0
    converged = False
    while not converged:
        converged = True
        for i in range(X.shape[0]):
            xi = X[i]
            yi = y[i]
            if yi * (xi.dot(w)) <= 0:
                loop += 1
                w += yi * xi
                converged = False
    return (w, loop)

def experiment(d, N, n_times=1000):
    loop_list = []
    grid = make_grid(1000)
    for i in range(n_times):
        X, y, line_coef = init(d, N)
        X_bar = np.hstack((np.ones([X.shape[0], 1]), X))
        w, loop = pla(X_bar, y)
        loop_list.append(loop)
    print('Average iters: {}'.format(np.mean(loop_list)))

In [265]:
experiment(2, 100, 1000)

Average iters: 137.115


NameError: name 'total_different_points' is not defined

In [260]:
a = np.array((1, 2, 3))

In [261]:
np.sign(a)

array([1, 1, 1])

In [262]:
b = np.array([-1, 2, 3])
np.sign(b)

array([-1,  1,  1])

In [263]:
np.sign(a) != np.sign(b)

array([ True, False, False])